#!/bin/bash

TEMPIN=$(tempfile -d /ssd/pdftoxml/)
TEMPOUT=$TEMPIN.xml

function cleanup() {
  rm -f $TEMPIN $TEMPOUT
}

trap cleanup EXIT

cp $1 $TEMPIN
timeout 10 pdftohtml -c -enc UTF-8 -xml -s -i $TEMPIN > /dev/null
cat $TEMPOUT
