#!/bin/bash

java\
 -agentlib:hprof=cpu=samples,interval=20,depth=64\
 -Xverify:none\
 -Xms512M\
 -Xmx1500M\
 -Xss1M\
 -XX:+UnlockExperimentalVMOptions\
 -XX:+CMSClassUnloadingEnabled\
 -XX:MaxPermSize=384M\
 -jar `dirname $0`/sbt-launch.jar "$@"
