#!/bin/bash

AUTOCITE_DIR=$PWD

pkill -f autocite
pdsh -g fast-beakers -R ssh pkill -f autocite &
sbt package generate-scripts || exit 1
wait

pdsh -g fast-beakers -R ssh $AUTOCITE_DIR/target/SearchWorker &
sleep 5
./target/SearchMaster &
./target/SearchApp &

disown %1 %2 %3
